-- MySQL Script generated by MySQL Workbench
-- Вт 30 окт 2018 16:31:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eShop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eShop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eShop` DEFAULT CHARACTER SET utf8 ;
USE `eShop` ;

-- -----------------------------------------------------
-- Table `eShop`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eShop`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eShop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eShop`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eShop`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eShop`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `comment` VARCHAR(200) NULL,
  `price` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_goods_country_idx` (`country_id` ASC),
  INDEX `fk_product_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `eShop`.`country` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `eShop`.`category` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eShop`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eShop`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `telefon_number` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eShop`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eShop`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `cost` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_client_idx` (`client_id` ASC),
  CONSTRAINT `fk_order_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `eShop`.`client` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eShop`.`order_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eShop`.`order_position` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_order_has_goods_goods_idx` (`product_id` ASC),
  INDEX `fk_order_has_goods_order_idx` (`order_id` ASC),
  CONSTRAINT `fk_list_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `eShop`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_list_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `eShop`.`product` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
