version: "2"

services:
  db:
    image: mysql:${MYSQL_TAG}
    command: --max_connections=300 --max_allowed_packet=67108864  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cpu_shares: 20
    memswap_limit: 1536m
    mem_limit: 1536m
    environment:
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=eShop
#    expose:
#      - "3306"
    ports:
      - "3306:3306"